import React, { useState, useEffect, memo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import {
  ArrowLeft,
  Star,
  Calendar,
  MessageCircle,
  Phone,
  Mail,
  MapPin,
  Shield,
  Clock,
  Users,
  Award,
  Globe,
  Share2,
  Heart,
  Zap
} from 'lucide-react';
import { Button } from '../../components/ui/button';
import { useAuthContext } from '../../contexts/AuthContext';
import { useVipContext } from '../../contexts/VipContext';
import razorpayService from '../../api/services/razorpayService';
import toast from 'react-hot-toast';

/**
 * VIP Page Component - Exact Flutter Parity
 * Features:
 * - VIP banner section
 * - VIP plan cards with pricing
 * - Payment integration
 * - Benefits display
 * - Responsive design
 */
const VipPage = () => {
  const navigate = useNavigate();
  const { user } = useAuthContext();
  const {
    vipPlans,
    loading,
    paymentLoading,
    selectedPlan,
    purchaseVipPlan,
    selectVipPlan,
    refreshVipData
  } = useVipContext();

  const handleBuyPlan = async (plan) => {
    try {
      selectVipPlan(plan);

      // Initialize Razorpay payment
      await razorpayService.openCheckout({
        total: parseFloat(plan.discount_price || plan.price),
        orderId: '', // Will be generated by backend
        onPaymentSuccess: async (paymentId) => {
          try {
            // Process VIP purchase using context
            const result = await purchaseVipPlan({
              planId: plan.id,
              paymentId: paymentId,
              amount: parseFloat(plan.discount_price || plan.price)
            });

            if (result.success) {
              navigate('/home');
            }
          } catch (error) {
            console.error('Error processing VIP purchase:', error);
          }
        },
        onPaymentError: (error) => {
          console.error('Payment failed:', error);
          toast.error('Payment failed. Please try again.');
        }
      });
    } catch (error) {
      console.error('Error initiating payment:', error);
      toast.error('Failed to initiate payment');
    }
  };

  const handleSeeBenefits = () => {
    // Navigate to VIP benefits detail page (to be implemented)
    toast.info('VIP benefits details coming soon!');
  };

  const formatCurrency = (amount) => {
    return `₹${Math.round(parseFloat(amount || 0))}`;
  };

  const getDurationText = (validityPeriod) => {
    const months = Math.floor(validityPeriod / 30);
    return `${months} month${months > 1 ? 's' : ''}`;
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <div className="w-12 h-12 border-4 border-gray-200 border-t-orange-500 rounded-full animate-spin"></div>
          <p className="text-gray-600 font-medium">Loading VIP Plans...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white">
      {/* Add CSS animations */}
      <style jsx>{`
        @keyframes gradient-shift {
          0%, 100% { background-position: 0% 50%; }
          50% { background-position: 100% 50%; }
        }

        @keyframes float {
          0%, 100% { transform: translateY(0px); }
          50% { transform: translateY(-10px); }
        }

        .gradient-shift {
          animation: gradient-shift 8s ease infinite;
        }

        .float-animation {
          animation: float 6s ease-in-out infinite;
        }
      `}</style>

      {/* Header */}
      <div className="sticky top-0 z-40 bg-white border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between py-3 h-14">
            <Button
              variant="ghost"
              onClick={() => navigate(-1)}
              className="p-2 hover:bg-gray-100 rounded-lg transition-colors duration-300"
            >
              <ArrowLeft className="w-5 h-5 text-gray-700" />
            </Button>
            <h1 className="text-lg font-bold text-gray-900">VIP Plans</h1>
            <div className="w-9"></div> {/* Spacer for center alignment */}
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto pb-6">
        {/* VIP Banner */}
        <motion.div
          className="px-4 sm:px-6 lg:px-8 pt-5 pb-8"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, ease: "easeOut" }}
        >
          <motion.div
            className="relative h-58 w-full rounded-2xl overflow-hidden shadow-lg"
            whileHover={{ scale: 1.02, y: -2 }}
            transition={{ duration: 0.3, ease: "easeOut" }}
          >
            <div
              className="absolute inset-0 bg-gradient-to-br from-orange-400 via-orange-500 to-orange-600"
              style={{
                backgroundImage: 'linear-gradient(135deg, #fb923c 0%, #f97316 50%, #ea580c 100%)',
                animation: 'gradient-shift 8s ease infinite'
              }}
            >
              {/* VIP Banner Content */}
              <div className="absolute inset-0 flex items-center justify-center">
                <motion.div
                  className="text-center text-white"
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ duration: 0.5, delay: 0.2 }}
                >
                  <div className="flex items-center justify-center mb-2">
                    <motion.div
                      animate={{ rotate: 360 }}
                      transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
                    >
                      <Star className="w-8 h-8 text-yellow-300 fill-yellow-300 mr-2" />
                    </motion.div>
                    <h2 className="text-2xl font-bold">VIP Membership</h2>
                    <motion.div
                      animate={{ rotate: -360 }}
                      transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
                    >
                      <Star className="w-8 h-8 text-yellow-300 fill-yellow-300 ml-2" />
                    </motion.div>
                  </div>
                  <motion.p
                    className="text-lg opacity-90"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 0.9 }}
                    transition={{ duration: 0.5, delay: 0.4 }}
                  >
                    Unlock Exclusive Benefits
                  </motion.p>
                  <motion.p
                    className="text-sm opacity-80 mt-1"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 0.8 }}
                    transition={{ duration: 0.5, delay: 0.6 }}
                  >
                    Save more on every order
                  </motion.p>
                </motion.div>
              </div>

              {/* Animated decorative elements */}
              <motion.div
                className="absolute top-4 right-4 w-16 h-16 bg-white bg-opacity-10 rounded-full"
                animate={{
                  scale: [1, 1.1, 1],
                  opacity: [0.1, 0.2, 0.1]
                }}
                transition={{
                  duration: 3,
                  repeat: Infinity,
                  ease: "easeInOut"
                }}
              />
              <motion.div
                className="absolute bottom-4 left-4 w-12 h-12 bg-white bg-opacity-10 rounded-full"
                animate={{
                  scale: [1, 1.2, 1],
                  opacity: [0.1, 0.15, 0.1]
                }}
                transition={{
                  duration: 4,
                  repeat: Infinity,
                  ease: "easeInOut",
                  delay: 1
                }}
              />
              <motion.div
                className="absolute top-1/2 left-8 w-8 h-8 bg-white bg-opacity-10 rounded-full"
                animate={{
                  scale: [1, 1.3, 1],
                  opacity: [0.1, 0.25, 0.1]
                }}
                transition={{
                  duration: 2.5,
                  repeat: Infinity,
                  ease: "easeInOut",
                  delay: 0.5
                }}
              />
            </div>
          </motion.div>
        </motion.div>

        {/* VIP Plans List */}
        <div className="px-4 sm:px-6 lg:px-8 space-y-4">
          {vipPlans.map((plan, index) => (
            <VipPlanCard
              key={plan.id}
              plan={plan}
              onBuyPlan={handleBuyPlan}
              onSeeBenefits={handleSeeBenefits}
              isLoading={paymentLoading && selectedPlan?.id === plan.id}
              formatCurrency={formatCurrency}
              getDurationText={getDurationText}
              index={index}
            />
          ))}
        </div>

        {/* Empty state */}
        {vipPlans.length === 0 && (
          <div className="px-4 sm:px-6 lg:px-8 py-12 text-center">
            <Star className="w-16 h-16 text-gray-300 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-gray-600 mb-2">No VIP Plans Available</h3>
            <p className="text-gray-500">VIP plans will be available soon!</p>
          </div>
        )}
      </div>

      {/* Attractive Footer */}
      <VipFooter />
    </div>
  );
};

// VIP Plan Card Component
const VipPlanCard = memo(({
  plan,
  onBuyPlan,
  onSeeBenefits,
  isLoading,
  formatCurrency,
  getDurationText,
  index
}) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, delay: index * 0.1, ease: "easeOut" }}
      whileHover={{
        scale: 1.02,
        y: -4,
        boxShadow: "0 20px 40px rgba(0,0,0,0.1)"
      }}
      whileTap={{ scale: 0.98 }}
      className="bg-white rounded-2xl shadow-lg border border-gray-100 overflow-hidden cursor-pointer"
    >
      <div className="p-6">
        <div className="flex items-start justify-between mb-4">
          {/* Plan Image and Duration */}
          <div className="flex items-center gap-4">
            {/* Plan Image */}
            <motion.div
              className="w-16 h-16 bg-gradient-to-br from-orange-100 to-orange-200 rounded-2xl flex items-center justify-center overflow-hidden"
              whileHover={{ scale: 1.05, rotate: 2 }}
              transition={{ duration: 0.2 }}
            >
              {plan.image ? (
                <motion.img
                  src={plan.image}
                  alt={plan.plan_name}
                  className="w-full h-full object-cover"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.3 }}
                  onError={(e) => {
                    e.target.style.display = 'none';
                    e.target.nextSibling.style.display = 'flex';
                  }}
                />
              ) : null}
              <motion.div
                className="w-full h-full flex items-center justify-center"
                animate={{ rotate: [0, 5, -5, 0] }}
                transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
              >
                <Star className="w-8 h-8 text-orange-500 fill-orange-500" />
              </motion.div>
            </motion.div>

            {/* Duration Badge */}
            <motion.div
              className="bg-orange-50 px-3 py-2 rounded-lg border border-orange-200"
              whileHover={{ scale: 1.05 }}
              transition={{ duration: 0.2 }}
            >
              <div className="flex items-center gap-2">
                <motion.div
                  animate={{ rotate: [0, 10, -10, 0] }}
                  transition={{ duration: 3, repeat: Infinity, ease: "easeInOut" }}
                >
                  <Calendar className="w-4 h-4 text-orange-600" />
                </motion.div>
                <div>
                  <p className="text-sm font-bold text-orange-600 leading-tight">
                    {getDurationText(plan.validity_period)}
                  </p>
                  <p className="text-xs text-orange-600 leading-tight">Plan</p>
                </div>
              </div>
            </motion.div>
          </div>

          {/* Pricing */}
          <motion.div
            className="text-right"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.3, delay: 0.2 }}
          >
            <div className="flex items-center gap-2 justify-end mb-1">
              {plan.price && plan.discount_price && plan.price !== plan.discount_price && (
                <motion.span
                  className="text-lg text-gray-400 line-through"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.3, delay: 0.3 }}
                >
                  {formatCurrency(plan.price)}
                </motion.span>
              )}
              <motion.span
                className="text-xl font-bold text-gray-900"
                initial={{ scale: 0.8, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                transition={{ duration: 0.3, delay: 0.4, type: "spring" }}
              >
                {formatCurrency(plan.discount_price || plan.price)}
              </motion.span>
            </div>
            <motion.button
              onClick={onSeeBenefits}
              className="text-sm text-orange-600 font-semibold underline hover:text-orange-700 transition-colors duration-300"
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.3, delay: 0.5 }}
            >
              See Benefits
            </motion.button>
          </motion.div>
        </div>

        {/* Plan Name and Description */}
        <div className="mb-4">
          <h3 className="text-lg font-bold text-gray-900 mb-1">{plan.plan_name}</h3>
          {plan.description && (
            <p className="text-sm text-gray-600 leading-relaxed">{plan.description}</p>
          )}
        </div>

        {/* Buy Button */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3, delay: 0.6 }}
        >
          <motion.div
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            transition={{ duration: 0.2 }}
          >
            <Button
              onClick={() => onBuyPlan(plan)}
              disabled={isLoading}
              className="w-full bg-gradient-to-r from-orange-500 to-orange-600 hover:from-orange-600 hover:to-orange-700 text-white font-bold py-3 px-6 rounded-xl transition-all duration-300 shadow-md hover:shadow-lg disabled:opacity-50 disabled:cursor-not-allowed relative overflow-hidden"
              style={{
                background: isLoading
                  ? 'linear-gradient(45deg, #f97316, #ea580c)'
                  : 'linear-gradient(45deg, #f97316, #ea580c, #f97316)',
                backgroundSize: '200% 200%',
                animation: isLoading ? 'none' : 'gradient-shift 3s ease infinite'
              }}
            >
              <AnimatePresence mode="wait">
                {isLoading ? (
                  <motion.div
                    key="loading"
                    className="flex items-center justify-center gap-2"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 0.2 }}
                  >
                    <motion.div
                      className="w-4 h-4 border-2 border-white border-t-transparent rounded-full"
                      animate={{ rotate: 360 }}
                      transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                    />
                    Processing...
                  </motion.div>
                ) : (
                  <motion.div
                    key="buy"
                    className="flex items-center justify-center gap-2"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 0.2 }}
                  >
                    <motion.div
                      animate={{ rotate: [0, 10, -10, 0] }}
                      transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
                    >
                      <Star className="w-4 h-4 fill-white" />
                    </motion.div>
                    Buy VIP Plan
                  </motion.div>
                )}
              </AnimatePresence>
            </Button>
          </motion.div>
        </motion.div>
      </div>
    </motion.div>
  );
});

VipPlanCard.displayName = 'VipPlanCard';

// VIP Footer Component
const VipFooter = memo(() => {
  const footerSections = [
    {
      title: "VIP Benefits",
      links: [
        { name: "Priority Support", href: "#", icon: Shield },
        { name: "Exclusive Discounts", href: "#", icon: Star },
        { name: "Fast Service", href: "#", icon: Clock },
        { name: "Premium Quality", href: "#", icon: Award }
      ]
    },
    {
      title: "Support",
      links: [
        { name: "Help Center", href: "#", icon: MessageCircle },
        { name: "Contact Us", href: "#", icon: Phone },
        { name: "FAQ", href: "#", icon: Mail },
        { name: "Live Chat", href: "#", icon: Users }
      ]
    },
    {
      title: "Company",
      links: [
        { name: "About Us", href: "#" },
        { name: "Terms of Service", href: "#" },
        { name: "Privacy Policy", href: "#" },
        { name: "Careers", href: "#" }
      ]
    }
  ];

  const socialLinks = [
    { name: "Website", icon: Globe, href: "#", color: "hover:text-blue-500" },
    { name: "Share", icon: Share2, href: "#", color: "hover:text-blue-400" },
    { name: "Community", icon: Heart, href: "#", color: "hover:text-pink-500" },
    { name: "Connect", icon: Zap, href: "#", color: "hover:text-yellow-500" }
  ];

  return (
    <motion.footer
      className="bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 text-white mt-16"
      initial={{ opacity: 0, y: 50 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6, ease: "easeOut" }}
    >
      {/* Main Footer Content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 lg:gap-12">
          {/* Company Info */}
          <motion.div
            className="lg:col-span-1"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
          >
            <div className="flex items-center mb-6">
              <motion.div
                className="w-10 h-10 bg-gradient-to-r from-orange-500 to-orange-600 rounded-xl flex items-center justify-center mr-3"
                whileHover={{ scale: 1.05, rotate: 5 }}
                transition={{ duration: 0.2 }}
              >
                <Star className="w-6 h-6 text-white fill-white" />
              </motion.div>
              <span className="text-2xl font-bold bg-gradient-to-r from-orange-400 to-orange-600 bg-clip-text text-transparent">
                EassyLife VIP
              </span>
            </div>
            <p className="text-gray-300 mb-6 leading-relaxed">
              Experience premium home services with exclusive VIP benefits.
              Join thousands of satisfied customers who trust us for quality and reliability.
            </p>

            {/* Contact Info */}
            <div className="space-y-3">
              <motion.div
                className="flex items-center text-gray-300 hover:text-orange-400 transition-colors duration-300"
                whileHover={{ x: 5 }}
                transition={{ duration: 0.2 }}
              >
                <Phone className="w-4 h-4 mr-3 flex-shrink-0" />
                <span className="text-sm">+91 1234 567 890</span>
              </motion.div>
              <motion.div
                className="flex items-center text-gray-300 hover:text-orange-400 transition-colors duration-300"
                whileHover={{ x: 5 }}
                transition={{ duration: 0.2 }}
              >
                <Mail className="w-4 h-4 mr-3 flex-shrink-0" />
                <span className="text-sm">vip@eassylife.com</span>
              </motion.div>
              <motion.div
                className="flex items-start text-gray-300 hover:text-orange-400 transition-colors duration-300"
                whileHover={{ x: 5 }}
                transition={{ duration: 0.2 }}
              >
                <MapPin className="w-4 h-4 mr-3 flex-shrink-0 mt-0.5" />
                <span className="text-sm">Mumbai, Maharashtra, India</span>
              </motion.div>
            </div>
          </motion.div>

          {/* Footer Sections */}
          {footerSections.map((section, sectionIndex) => (
            <motion.div
              key={section.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 + sectionIndex * 0.1 }}
            >
              <h3 className="text-lg font-semibold mb-6 text-white">
                {section.title}
              </h3>
              <ul className="space-y-3">
                {section.links.map((link, linkIndex) => (
                  <motion.li
                    key={link.name}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.3, delay: 0.3 + linkIndex * 0.05 }}
                  >
                    <motion.a
                      href={link.href}
                      className="flex items-center text-gray-300 hover:text-orange-400 transition-all duration-300 group"
                      whileHover={{ x: 5 }}
                      transition={{ duration: 0.2 }}
                    >
                      {link.icon && (
                        <link.icon className="w-4 h-4 mr-3 flex-shrink-0 group-hover:text-orange-400 transition-colors duration-300" />
                      )}
                      <span className="text-sm group-hover:underline">
                        {link.name}
                      </span>
                    </motion.a>
                  </motion.li>
                ))}
              </ul>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Bottom Footer */}
      <div className="border-t border-gray-700">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            {/* Copyright */}
            <motion.div
              className="text-center md:text-left"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5, delay: 0.6 }}
            >
              <p className="text-gray-400 text-sm">
                © 2024 EassyLife. All rights reserved. | VIP Membership Program
              </p>
            </motion.div>

            {/* Social Links */}
            <motion.div
              className="flex items-center space-x-4"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.7 }}
            >
              {socialLinks.map((social, index) => (
                <motion.a
                  key={social.name}
                  href={social.href}
                  className={`w-10 h-10 bg-gray-700 rounded-full flex items-center justify-center text-gray-300 hover:bg-gray-600 transition-all duration-300 ${social.color}`}
                  whileHover={{ scale: 1.1, y: -2 }}
                  whileTap={{ scale: 0.95 }}
                  initial={{ opacity: 0, scale: 0.8 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ duration: 0.3, delay: 0.8 + index * 0.1 }}
                  aria-label={social.name}
                >
                  <social.icon className="w-5 h-5" />
                </motion.a>
              ))}
            </motion.div>
          </div>
        </div>
      </div>

      {/* Decorative Elements */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <motion.div
          className="absolute -top-24 -right-24 w-48 h-48 bg-orange-500 bg-opacity-5 rounded-full"
          animate={{
            scale: [1, 1.1, 1],
            opacity: [0.05, 0.1, 0.05]
          }}
          transition={{
            duration: 8,
            repeat: Infinity,
            ease: "easeInOut"
          }}
        />
        <motion.div
          className="absolute -bottom-12 -left-12 w-32 h-32 bg-orange-400 bg-opacity-5 rounded-full"
          animate={{
            scale: [1, 1.2, 1],
            opacity: [0.05, 0.08, 0.05]
          }}
          transition={{
            duration: 6,
            repeat: Infinity,
            ease: "easeInOut",
            delay: 2
          }}
        />
      </div>
    </motion.footer>
  );
});

VipFooter.displayName = 'VipFooter';

export default memo(VipPage);
